baseURL = "http://designthinkmakebreakrepeat.com/"
googleAnalytics = "UA-31178888-6"
languageCode = "en-us"
title = "Design. Think. Make. Break. Repeat."
theme = "dtmbr"
[params.intro]
  buttontext = "Buy The Book"
[params.navigation]
  title = "Design. Think. Make. Break. Repeat."
[params.footer]
  enable = true
  copyright = "Copyright 2021 - Design. Think. Make. Break. Repeat."
  publisher = "BIS Publishers"
  url = "http://www.bispublishers.com/"
