name = "DTMBR"
license = "Creative Commons Attribution 3.0"
licenselink = ""
description = ""
homepage = ""
tags = ["portfolio", "company", "contact form", "google analytics", "blog"]
features = ["blog"]
min_version = "0.29"

[author]
  name = "Marcus Virginia"
  homepage = "https://marcusv.me"

# If porting an existing theme
[original]
  author = "AJ"
  name = "HTML5 Up"
  homepage = "https://html5up.net/forty"
