---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static/uploads/templates
public_path: "/uploads/templates"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.31.1
